name: Deploy Frontend to VPS

on:
  push:
    branches:
      - main # Robot akan bekerja setiap kali ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Eksekusi proses deploy di VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            script: |
            # Masuk ke folder proyek Frontend
            cd ~/SadewasHub-FE

            # Tarik kode terbaru
            git pull origin main

            # 🌟 PERBAIKAN: Hapus kata sudo di bawah ini
            docker compose up -d --build
            docker image prune -f
